#ifndef COUNTER_MODBUS_NODE_CONFIG_H
#define COUNTER_MODBUS_NODE_CONFIG_H
#include "secrets.h"

#define HOME_NAME SECRETS_HOME_NAME
#define HTTP_ENDPOINT_HOSTNAME SECRETS_HTTP_ENDPOINT_HOSTNAME
#define HTTP_ENDPOINT_PORT SECRETS_HTTP_ENDPOINT_PORT
#define HTTP_ENDPOINT_PATH SECRETS_HTTP_ENDPOINT_PATH

#define ESP_WIFI_SSID      SECRETS_ESP_WIFI_SSID
#define ESP_WIFI_PASS      SECRETS_ESP_WIFI_PASSWORD
#define ESP_MAXIMUM_RETRY  10

#define MAX_HTTP_RECV_BUFFER 512
#define MAX_HTTP_OUTPUT_BUFFER 1024

#define MB_UART_PORT    UART_NUM_1
#define MB_BAUD_RATE    9600
#define MB_SLAVE_ADDR   1

#endif //COUNTER_MODBUS_NODE_CONFIG_H
