#ifndef COUNTER_MODBUS_NODE_SECRETS_H
#define COUNTER_MODBUS_NODE_SECRETS_H

#define SECRETS_ESP_WIFI_SSID "ssid"
#define SECRETS_ESP_WIFI_PASSWORD "password"
#define SECRETS_HTTP_ENDPOINT_HOSTNAME "API"
#define SECRETS_HTTP_ENDPOINT_PATH "/endpoint_path"
#define SECRETS_HTTP_ENDPOINT_PORT 8004
#define SECRETS_HOME_ID "HOME ID"


#endif //COUNTER_MODBUS_NODE_SECRETS_H
